name: Unzip File
on: workflow_dispatch

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Unzip file
        run: |
          unzip eas_educstuion-main (2).zip -d folder_hasil
          rm eas_educstuion-main (2).zip
          
      - name: Commit hasil unzip
        run: |
          git config --global user.name 'Bot Kimi'
          git config --global user.email 'bot@kimi.dev'
          git add .
          git commit -m "Unzip by Kimi 🔥"
          git push
